version: "3.8"

services:
  workshop-app:
    container_name: golang-api
    build:
      context: .
      dockerfile: ./build/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env

networks:
  default:
    external:
      name: otoklix
